ilto4/protected/models/Answers.php
<?php

/**
 * This is the model class for table "answers".
 *
 * The followings are the available columns in table 'answers':
 * @property integer $id_respuesta
 * @property integer $id_pregunta
 * @property string $ruta_imagen
 * @property string $ruta_video
 * @property string $ruta_audio
 * @property string $texto
 * @property integer $es_verdadera
 *
 * The followings are the available model relations:
 * @property Questions $idPregunta
 * @property AnswersExamUser[] $answersExamUsers
 */
class Answers extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'answers';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_pregunta, estado', 'required'),
			array('id_pregunta, es_verdadera', 'numerical', 'integerOnly'=>true),
			array('ruta_imagen, ruta_video, ruta_audio', 'length', 'max'=>200),
			array('texto, estado', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id_respuesta, id_pregunta, ruta_imagen, ruta_video, ruta_audio, texto, es_verdadera', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'idPregunta' => array(self::BELONGS_TO, 'Questions', 'id_pregunta'),
			'answersExamUsers' => array(self::HAS_MANY, 'AnswersExamUser', 'id_respuesta'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id_respuesta' => 'Id ',
			'id_pregunta' => 'Question',
			'ruta_imagen' => 'Image',
			'ruta_video' => 'Video',
			'ruta_audio' => 'Audio',
			'estado' => 'Status',
			'texto' => 'Text',
			'es_verdadera' => 'Correct',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id_respuesta',$this->id_respuesta);
		$criteria->compare('id_pregunta',$this->id_pregunta);
		$criteria->compare('ruta_imagen',$this->ruta_imagen,true);
		$criteria->compare('ruta_video',$this->ruta_video,true);
		$criteria->compare('ruta_audio',$this->ruta_audio,true);
		$criteria->compare('estado',$this->estado,true);
		$criteria->compare('texto',$this->texto,true);
		$criteria->compare('es_verdadera',$this->es_verdadera);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
                    'pagination'=>array('pageSize'=>50,),

		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Answers the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

ilto4/protected/controllers/AnswersController.php
<?php

class AnswersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','admin','delete'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array(),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($question)
	{
		$model=new Answers;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Answers']))
		{
                        $model->attributes=$_POST['Answers'];
                        $ruta_imagen=CUploadedFile::getInstance($model,'ruta_imagen');
                        $ruta_audio=CUploadedFile::getInstance($model,'ruta_audio');
                        $ahora = time();
			if($model->save()){
                            if($model->es_verdadera==true){
                                //Marcar las otras respuestas como falsas
                                $modelRespuestas = Answers::model()->findAllByAttributes(array('id_pregunta'=>$question));
                                foreach($modelRespuestas as $rowRespuesta){
                                    $rowRespuesta->es_verdadera = 0;
                                    $rowRespuesta->save(true,array('es_verdadera'));
                                }
                                $model->es_verdadera=1;
                                $model->save(true,array('es_verdadera'));
                            }
                            $modUtil = new Utilidades();
                            if(!is_null($ruta_imagen)){
                                $extension = ".".$ruta_imagen->getExtensionName();
                                $nombreImagen = $model->id_pregunta."_".$ahora.$extension;
                                $model->ruta_imagen=$nombreImagen;
                                $model->save();
                                $ruta_imagen->saveAs("images/answers/".$nombreImagen);
                                $modUtil->generaThumb("images/answers/",$nombreImagen);
                            }
                            if(!is_null($ruta_audio)){
                                $nombreAudio = 'audio/answers/'.$model->id_pregunta."_".$ahora.".mp3";
                                $model->ruta_audio=$nombreAudio;
                                $model->save();
                                $ruta_audio->saveAs($nombreAudio);
                            }
				$this->redirect(array('admin','question'=>$question));
                        }
		}

		$this->render('create',array(
			'model'=>$model,'question'=>$question
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id,$question)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Answers']))
		{
                        $modAnt = $this->loadModel($id);
			$model->attributes=$_POST['Answers'];
                        $ruta_imagen=CUploadedFile::getInstance($model,'ruta_imagen');
                        $ruta_audio=CUploadedFile::getInstance($model,'ruta_audio');
                        $ahora = time();
			if($model->save(true,array('texto','estado','es_verdadera'))){
                            if($model->es_verdadera==true){
                                //Marcar las otras respuestas como falsas
                                $modelRespuestas = Answers::model()->findAllByAttributes(array('id_pregunta'=>$question));
                                foreach($modelRespuestas as $rowRespuesta){
                                    $rowRespuesta->es_verdadera = 0;
                                    $rowRespuesta->save(true,array('es_verdadera'));
                                }
                                $model->es_verdadera=1;
                                $model->save(true,array('es_verdadera'));
                            }
                            $modUtil = new Utilidades();
                                if(!is_null($ruta_imagen)){
                                    //Si tenia una imagen, eliminarla
                                    if(isset($_POST['ruta_imagen_actual'])){
                                        $modUtil->eliminarThumbs("images/answers/",$_POST['ruta_imagen_actual']);
                                    }
                                    //Nombre de la nueva imagen
                                    $extension = ".".$ruta_imagen->getExtensionName();
                                    $nombreImagen = $model->id_pregunta."_".$ahora.$extension;
                                    $model->ruta_imagen=$nombreImagen;
                                    $model->save();
                                    $ruta_imagen->saveAs("images/answers/".$nombreImagen);
                                    $modUtil->generaThumb("images/answers/",$nombreImagen);
                                } elseif(strlen($_POST['ruta_imagen_actual'])>0){ //Si existia una imagen previa
                                    if(isset($_POST['delete_imagen'])){
                                        $model->ruta_imagen=NULL;
                                        $model->save(true,array('ruta_imagen'));
                                        $modUtil->eliminarThumbs("images/answers/",$_POST['ruta_imagen_actual']);
                                    }
                                }
                                if(!is_null($ruta_audio)){
                                    //Si tenia una imagen, eliminarla
                                    if(isset($_POST['ruta_audio_actual'])){
                                        @unlink($_POST['ruta_audio_actual']);
                                    }
                                    //Nombre de la nueva imagen
                                    $nombreAudio = 'audio/answers/'.$model->id_pregunta."_".$ahora.".mp3";
                                    $model->ruta_audio=$nombreAudio;
                                    $model->save();
                                    $ruta_audio->saveAs($nombreAudio);
                                } elseif(strlen($_POST['ruta_audio_actual'])>0){ //Si existia un archivo previa
                                    if(isset($_POST['delete_audio'])){
                                        @unlink($_POST['ruta_audio_actual']); //Eliminar el audio actual
                                        $model->ruta_audio = NULL;
                                        $model->save(true,array('ruta_audio'));
                                    }
                                }
				$this->redirect(array('admin','question'=>$question));
                        }
		}

		$this->render('update',array(
			'model'=>$model,'question'=>$question
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Answers');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin($question=NULL)
	{
		$model=new Answers('search');
		$model->unsetAttributes();  // clear any default values
                if(!is_null($question)){
                    $model->id_pregunta = $question;
                }
		if(isset($_GET['Answers']))
			$model->attributes=$_GET['Answers'];

		$this->render('admin',array(
			'model'=>$model,'question'=>$question
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Answers the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Answers::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Answers $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='answers-form')
		{

ilto4/protected/views/answers/_form.php
<?php
/* @var $this AnswersController */
/* @var $model Answers */
/* @var $form CActiveForm */
$modUtil= new Utilidades();

?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'answers-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
    'htmlOptions' => array(
        'enctype' => 'multipart/form-data',
    ),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

       	<div class="row">
                <?php echo $form->labelEx($model,'texto'); ?>
		<?php echo $form->textArea($model,'texto',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'texto'); ?>
	</div>

	<?php echo $form->errorSummary($model); ?>
	<div class="row">
		<?php echo $form->labelEx($model,'ruta_imagen'); ?>
		<?php echo $form->fileField($model,'ruta_imagen'); ?>
		<?php echo $form->error($model,'ruta_imagen'); ?>
            <?php if(!$model->isNewRecord){
                if(strlen($model->ruta_imagen)>0){
                    echo "<img src='images/answers/tn2_$model->ruta_imagen' style='width:200px;'>";
                    echo "<input type='hidden' name='ruta_imagen_actual' value='$model->ruta_imagen'>";
                    echo "&nbsp;&nbsp;<input type='checkbox' name='delete_imagen' value='1'>&nbsp;Delete Image on Save";
                }
            } ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'ruta_video'); ?>
		<?php echo $form->textField($model,'ruta_video',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'ruta_video'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'ruta_audio'); ?>
		<?php echo $form->fileField($model,'ruta_audio'); ?>
		<?php echo $form->error($model,'ruta_audio'); ?>
            <?php if(!$model->isNewRecord){
                if(strlen($model->ruta_audio)>0){
                    echo "<audio controls><source src='$model->ruta_audio' type='audio/wav'></audio>";
                    echo "<input type='hidden' name='ruta_audio_actual' value='$model->ruta_audio'>";
                    echo "&nbsp;&nbsp;<input type='checkbox' name='delete_audio' value='1'>&nbsp;Delete Audio on Save";
                }
            } ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'es_verdadera'); ?>
		<?php echo $form->checkBox($model,'es_verdadera'); ?>
		<?php echo $form->error($model,'es_verdadera'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'estado'); ?>
		<?php
            $dataCombo=array('A'=>'Enabled','I'=>'Disabled');
            $this->widget('ext.select2.ESelect2',array(
            'name'=>'Answers[estado]',
            'id'=> 'combo_estado',
            'data'=>$dataCombo,
                'value'=>$model->estado,
            'options'=>array(
              'placeholder'=>'Choose one...',
              'allowClear'=>true,
                'width'=>'220px',
            ),
          ));
            ?>
		<?php echo $form->error($model,'estado'); ?>
	</div>

	<div class="row buttons">
		<?php 
                //$model->id_pregunta = $question;
                echo $form->hiddenField($model,'id_pregunta',array('value'=>$question)); 
                echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

ilto4/protected/views/answers/_search.php
<?php
/* @var $this AnswersController */
/* @var $model Answers */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id_respuesta'); ?>
		<?php echo $form->textField($model,'id_respuesta'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'id_pregunta'); ?>
		<?php echo $form->textField($model,'id_pregunta'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ruta_imagen'); ?>
		<?php echo $form->textField($model,'ruta_imagen',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ruta_video'); ?>
		<?php echo $form->textField($model,'ruta_video',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ruta_audio'); ?>
		<?php echo $form->textField($model,'ruta_audio',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'texto'); ?>
		<?php echo $form->textArea($model,'texto',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'es_verdadera'); ?>
		<?php echo $form->textField($model,'es_verdadera'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

ilto4/protected/views/answers/_view.php
<?php
/* @var $this AnswersController */
/* @var $data Answers */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id_respuesta')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id_respuesta), array('view', 'id'=>$data->id_respuesta)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('id_pregunta')); ?>:</b>
	<?php echo CHtml::encode($data->id_pregunta); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ruta_imagen')); ?>:</b>
	<?php echo CHtml::encode($data->ruta_imagen); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ruta_video')); ?>:</b>
	<?php echo CHtml::encode($data->ruta_video); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ruta_audio')); ?>:</b>
	<?php echo CHtml::encode($data->ruta_audio); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('texto')); ?>:</b>
	<?php echo CHtml::encode($data->texto); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('es_verdadera')); ?>:</b>
	<?php echo CHtml::encode($data->es_verdadera); ?>
	<br />


</div>

ilto4/protected/views/answers/admin.php
<?php
/* @var $this AnswersController */
/* @var $model Answers */

$this->breadcrumbs=array(
	'Answers'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'Go Back to Questions', 'url'=>array('questions/admin')),
	array('label'=>'Create Answers', 'url'=>array('create','question'=>$question)),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#answers-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Answers for....ID:<?php echo $question;?></h1>
<div>
    <?php
        echo Questions::model()->findByPk($question)->texto;
    ?>
</div>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'answers-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
            'id_respuesta',
            'id_pregunta',
            array(
                'name'=>'texto',
                'type'=>'raw'
            ),
            array(
                'name'=>'ruta_imagen',
                'filter'=>'',
                'value'=>'(!empty($data->ruta_imagen))?CHtml::image(Yii::app()->baseUrl."/images/answers/tn1_".$data->ruta_imagen,"",array("class"=>"imagen", "href"=>Yii::app()->baseUrl."/images/answers/tn3_$data->ruta_imagen","style"=>"width:150px !important; max-width:100% !important;")):"no image"',
                'type'=>'raw'
                ),
            array(
                'name'=>'ruta_audio',
                'filter'=>'',
                'type'=>'raw',
                'value'=>'(!empty($data->ruta_audio))? "<audio controls><source src=\'$data->ruta_audio\' type=\'audio/wav\'></audio>" : "No Audio"',
            ),
                array(
                    'name'=>'estado',
                    'value'=>'($data->estado=="A" ? "Enabled" : "Disabled")',
                    'filter'=>array("A"=>"Enable","I"=>"Disable"),
                    ),
                array(
                    'name'=>'es_verdadera',
                    'value'=>'(($data->es_verdadera))?CHtml::image(Yii::app()->baseUrl."/images/iconos/ok.png","",array("style"=>"max-width:20px;")):CHtml::image(Yii::app()->baseUrl."/images/iconos/delete.png","",array("style"=>"max-width:20px;"))',                    
                    'filter'=>'',
                    'type'=>'raw',
                    ),
		array(
			'class'=>'CButtonColumn',
                    'template'=>'{update}{delete}',
                    'buttons'=>array(
                        'update'=>array(
                            'label'=>'Edit&nbsp;',
                            'url'=> 'Yii::app()->createUrl("answers/update",array("id"=>$data->id_respuesta,"question"=>$data->id_pregunta))',
                            'imageUrl' => NULL,
                    ),
                        'delete'=>array(
                            'label'=>'Delete',
                            'imageUrl'=>NULL, 
                        ))
		),
	),
)); ?>

ilto4/protected/views/answers/create.php
<?php
/* @var $this AnswersController */
/* @var $model Answers */

$this->breadcrumbs=array(
	'Answers'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'Manage Answers', 'url'=>array('admin','question'=>$question)),
);
?>

<h1>Create Answers</h1>

<?php $this->renderPartial('_form', array('model'=>$model,'question'=>$question)); ?>

ilto4/protected/views/answers/index.php
<?php
/* @var $this AnswersController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Answers',
);

$this->menu=array(
	array('label'=>'Create Answers', 'url'=>array('create')),
	array('label'=>'Manage Answers', 'url'=>array('admin')),
);
?>

<h1>Answers</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

ilto4/protected/views/answers/update.php
<?php
/* @var $this AnswersController */
/* @var $model Answers */

$this->breadcrumbs=array(
	'Answers'=>array('index'),
	$model->id_respuesta=>array('view','id'=>$model->id_respuesta),
	'Update',
);

$this->menu=array(
	array('label'=>'Create Answers', 'url'=>array('create','question'=>$question)),
	array('label'=>'Manage Answers', 'url'=>array('admin','question'=>$question)),
);
?>

<h1>Update Answers <?php echo $model->id_respuesta; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

ilto4/protected/views/answers/view.php
<?php
/* @var $this AnswersController */
/* @var $model Answers */

$this->breadcrumbs=array(
	'Answers'=>array('index'),
	$model->id_respuesta,
);

$this->menu=array(
	array('label'=>'List Answers', 'url'=>array('index')),
	array('label'=>'Create Answers', 'url'=>array('create')),
	array('label'=>'Update Answers', 'url'=>array('update', 'id'=>$model->id_respuesta)),
	array('label'=>'Delete Answers', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id_respuesta),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Answers', 'url'=>array('admin')),
);
?>

<h1>View Answers #<?php echo $model->id_respuesta; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id_respuesta',
		'id_pregunta',
		'ruta_imagen',
		'ruta_video',
		'ruta_audio',
		'texto',
		'es_verdadera',
	),
)); ?>